"""Generate TypeScript from the public Pydantic models (no codegen dependency)."""
import json
import sys
from pathlib import Path
from models import Playbook, PlayerMatches, History, TrackedPlayer


def ts(schema):
    if '$ref' in schema:
        return schema['$ref'].split('/')[-1]
    if 'const' in schema:
        return json.dumps(schema['const'])
    if 'enum' in schema:
        return ' | '.join(json.dumps(v) for v in schema['enum'])
    if 'anyOf' in schema:
        return ' | '.join(ts(s) for s in schema['anyOf'])
    kind=schema.get('type')
    if kind=='array':
        return f'Array<{ts(schema["items"])}>'
    if kind=='object':
        return '{\n'+'\n'.join(f'  {name}: {ts(value)};' for name,value in schema.get('properties',{}).items())+'\n}'
    return {'integer':'number','number':'number','boolean':'boolean','string':'string','null':'null'}[kind]


def generate():
    definitions={}
    for model in (Playbook,PlayerMatches,History,TrackedPlayer):
        schema=model.model_json_schema()
        definitions.update(schema.pop('$defs',{}))
        definitions[model.__name__]=schema
    types='\n\n'.join(f'export type {name} = {ts(schema)};' for name,schema in definitions.items())
    guards='\n\n'.join(f'export function is{name}(value: unknown): value is {name} {{\n  return {guard(schema,"value")};\n}}' for name,schema in definitions.items())
    return '// Generated by macrolab-backend/export_contract.py. Do not edit.\n'+types+'\n\nfunction isRecord(value: unknown): value is Record<string, unknown> {\n  return typeof value === "object" && value !== null && !Array.isArray(value);\n}\n\n'+guards+'\n'


def guard(schema, value):
    if '$ref' in schema:
        return f'is{schema["$ref"].split("/")[-1]}({value})'
    if 'const' in schema:
        return f'{value} === {json.dumps(schema["const"])}'
    if 'enum' in schema:
        return '('+' || '.join(f'{value} === {json.dumps(v)}' for v in schema['enum'])+')'
    if 'anyOf' in schema:
        return '('+' || '.join(guard(s,value) for s in schema['anyOf'])+')'
    kind=schema.get('type')
    if kind=='array': return f'Array.isArray({value}) && {value}.every(item => {guard(schema["items"],"item")})'
    if kind=='object': return ' &&\n    '.join([f'isRecord({value})']+[guard(s,f'{value}.{k}') for k,s in schema.get('properties',{}).items()])
    if kind=='null': return f'{value} === null'
    if kind in ('number','integer'):
        parts=[f'typeof {value} === "number"',f'Number.isFinite({value})']
        if kind=='integer': parts.append(f'Number.isInteger({value})')
        for key,operator in [('minimum','>='),('maximum','<='),('exclusiveMinimum','>'),('exclusiveMaximum','<')]:
            if key in schema: parts.append(f'{value} {operator} {schema[key]}')
        return ' && '.join(parts)
    return f'typeof {value} === "{kind}"'


if __name__=='__main__':
    target=Path(sys.argv[1])
    if '--check' in sys.argv:
        assert target.read_text(encoding='utf-8')==generate(), 'Regenerate the frontend contract'
    else:
        target.write_text(generate(),encoding='utf-8')
