// Generated by macrolab-backend/export_contract.py. Do not edit.
export type Alternative = {
  label: string;
  tradeoff: string;
};

export type Decision = {
  id: string;
  rule_id: string;
  timestamp: number;
  title: string;
  prompt: string;
  facts: Array<string>;
  interpretation: string;
  evidence_ids: Array<string>;
  alternatives: Array<Alternative>;
  limitations: Array<string>;
  confidence: "observed_sequence";
  context: Array<string>;
};

export type Evaluation = {
  key: string;
  name: string;
  score: number;
  reason: string;
};

export type Event = {
  id: string;
  type: "WARD_PLACED" | "CHAMPION_KILL" | "ELITE_MONSTER_KILL" | "BUILDING_KILL" | "ITEM_PURCHASED";
  timestamp: number;
  detail: string;
  position_pct: Position | null;
  position_estimated: boolean;
};

export type GamePlan = {
  win_condition: string;
  phases: Array<Phase>;
};

export type HabitMetric = {
  eligible: boolean;
  numerator: number;
  denominator: number;
};

export type Phase = {
  title: string;
  start: number;
  end: number | null;
  action: string;
};

export type Pick = {
  champion_name: string;
  champion_id: number;
  role: string;
};

export type Position = {
  x: number;
  y: number;
};

export type RoutePoint = {
  timestamp: number;
  position_pct: Position;
};

export type Stats = {
  champion_name: string;
  champion_id: number;
  role: string;
  team_id: number;
  win: boolean;
  game_created_at: number;
  duration_seconds: number;
  queue_id: number;
  patch: string;
  kills: number | null;
  deaths: number | null;
  assists: number | null;
  kda: number | null;
  cs_per_min: number | null;
  vision_score: number | null;
  vision_per_min: number | null;
  damage_per_min: number | null;
  gold_per_min: number | null;
  wards_placed: number | null;
  wards_killed: number | null;
  turret_damage: number | null;
  kill_participation_pct: number | null;
  lane_opponent: string | null;
  cs_delta: number | null;
  gold_delta: number | null;
};

export type Playbook = {
  schema_version: 2;
  analysis_version: string;
  match_id: string;
  data_source: "riot" | "demo";
  status: "ready" | "unsupported" | "insufficient_data";
  queue_id: number | null;
  map_id: number | null;
  patch: string;
  data_quality: Array<string>;
  archetype: string;
  model_key: string;
  model_reason: string;
  model_evaluation: Array<Evaluation>;
  composition: Array<Pick>;
  enemy_composition: Array<Pick>;
  match_stats: Stats | null;
  game_plan: GamePlan | null;
  player_route: Array<RoutePoint>;
  events: Array<Event>;
  decisions: Array<Decision>;
  habit_metric: HabitMetric;
  saved: boolean;
};

export type Account = {
  puuid: string;
  gameName: string;
  tagLine: string;
};

export type PlayerMatches = {
  account: Account;
  matches: Array<string>;
};

export type FeedbackSummary = {
  decision: string;
  verdict: "agree" | "context" | "incorrect";
  comment: string;
  match_id: string;
  created: number;
};

export type HabitProgress = {
  started: number;
  version: string;
  completed: number;
  target: 5;
  numerator: number;
  denominator: number;
};

export type ShareSummary = {
  token: string;
  match_id: string;
  expires: number;
};

export type History = {
  analyses: Array<Playbook>;
  habit: HabitProgress | null;
  shares: Array<ShareSummary>;
  feedback: Array<FeedbackSummary>;
};

export type TrackedPlayer = {
  puuid: string;
  name: string;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function isAlternative(value: unknown): value is Alternative {
  return isRecord(value) &&
    typeof value.label === "string" &&
    typeof value.tradeoff === "string";
}

export function isDecision(value: unknown): value is Decision {
  return isRecord(value) &&
    typeof value.id === "string" &&
    typeof value.rule_id === "string" &&
    typeof value.timestamp === "number" && Number.isFinite(value.timestamp) && Number.isInteger(value.timestamp) &&
    typeof value.title === "string" &&
    typeof value.prompt === "string" &&
    Array.isArray(value.facts) && value.facts.every(item => typeof item === "string") &&
    typeof value.interpretation === "string" &&
    Array.isArray(value.evidence_ids) && value.evidence_ids.every(item => typeof item === "string") &&
    Array.isArray(value.alternatives) && value.alternatives.every(item => isAlternative(item)) &&
    Array.isArray(value.limitations) && value.limitations.every(item => typeof item === "string") &&
    value.confidence === "observed_sequence" &&
    Array.isArray(value.context) && value.context.every(item => typeof item === "string");
}

export function isEvaluation(value: unknown): value is Evaluation {
  return isRecord(value) &&
    typeof value.key === "string" &&
    typeof value.name === "string" &&
    typeof value.score === "number" && Number.isFinite(value.score) && Number.isInteger(value.score) &&
    typeof value.reason === "string";
}

export function isEvent(value: unknown): value is Event {
  return isRecord(value) &&
    typeof value.id === "string" &&
    (value.type === "WARD_PLACED" || value.type === "CHAMPION_KILL" || value.type === "ELITE_MONSTER_KILL" || value.type === "BUILDING_KILL" || value.type === "ITEM_PURCHASED") &&
    typeof value.timestamp === "number" && Number.isFinite(value.timestamp) && Number.isInteger(value.timestamp) && value.timestamp >= 0 &&
    typeof value.detail === "string" &&
    (isPosition(value.position_pct) || value.position_pct === null) &&
    typeof value.position_estimated === "boolean";
}

export function isGamePlan(value: unknown): value is GamePlan {
  return isRecord(value) &&
    typeof value.win_condition === "string" &&
    Array.isArray(value.phases) && value.phases.every(item => isPhase(item));
}

export function isHabitMetric(value: unknown): value is HabitMetric {
  return isRecord(value) &&
    typeof value.eligible === "boolean" &&
    typeof value.numerator === "number" && Number.isFinite(value.numerator) && Number.isInteger(value.numerator) &&
    typeof value.denominator === "number" && Number.isFinite(value.denominator) && Number.isInteger(value.denominator);
}

export function isPhase(value: unknown): value is Phase {
  return isRecord(value) &&
    typeof value.title === "string" &&
    typeof value.start === "number" && Number.isFinite(value.start) && Number.isInteger(value.start) &&
    (typeof value.end === "number" && Number.isFinite(value.end) && Number.isInteger(value.end) || value.end === null) &&
    typeof value.action === "string";
}

export function isPick(value: unknown): value is Pick {
  return isRecord(value) &&
    typeof value.champion_name === "string" &&
    typeof value.champion_id === "number" && Number.isFinite(value.champion_id) && Number.isInteger(value.champion_id) &&
    typeof value.role === "string";
}

export function isPosition(value: unknown): value is Position {
  return isRecord(value) &&
    typeof value.x === "number" && Number.isFinite(value.x) && value.x >= 0 && value.x <= 100 &&
    typeof value.y === "number" && Number.isFinite(value.y) && value.y >= 0 && value.y <= 100;
}

export function isRoutePoint(value: unknown): value is RoutePoint {
  return isRecord(value) &&
    typeof value.timestamp === "number" && Number.isFinite(value.timestamp) && Number.isInteger(value.timestamp) && value.timestamp >= 0 &&
    isPosition(value.position_pct);
}

export function isStats(value: unknown): value is Stats {
  return isRecord(value) &&
    typeof value.champion_name === "string" &&
    typeof value.champion_id === "number" && Number.isFinite(value.champion_id) && Number.isInteger(value.champion_id) &&
    typeof value.role === "string" &&
    typeof value.team_id === "number" && Number.isFinite(value.team_id) && Number.isInteger(value.team_id) &&
    typeof value.win === "boolean" &&
    typeof value.game_created_at === "number" && Number.isFinite(value.game_created_at) && Number.isInteger(value.game_created_at) &&
    typeof value.duration_seconds === "number" && Number.isFinite(value.duration_seconds) && Number.isInteger(value.duration_seconds) && value.duration_seconds > 0 &&
    typeof value.queue_id === "number" && Number.isFinite(value.queue_id) && Number.isInteger(value.queue_id) &&
    typeof value.patch === "string" &&
    (typeof value.kills === "number" && Number.isFinite(value.kills) && Number.isInteger(value.kills) || value.kills === null) &&
    (typeof value.deaths === "number" && Number.isFinite(value.deaths) && Number.isInteger(value.deaths) || value.deaths === null) &&
    (typeof value.assists === "number" && Number.isFinite(value.assists) && Number.isInteger(value.assists) || value.assists === null) &&
    (typeof value.kda === "number" && Number.isFinite(value.kda) || value.kda === null) &&
    (typeof value.cs_per_min === "number" && Number.isFinite(value.cs_per_min) || value.cs_per_min === null) &&
    (typeof value.vision_score === "number" && Number.isFinite(value.vision_score) || value.vision_score === null) &&
    (typeof value.vision_per_min === "number" && Number.isFinite(value.vision_per_min) || value.vision_per_min === null) &&
    (typeof value.damage_per_min === "number" && Number.isFinite(value.damage_per_min) || value.damage_per_min === null) &&
    (typeof value.gold_per_min === "number" && Number.isFinite(value.gold_per_min) || value.gold_per_min === null) &&
    (typeof value.wards_placed === "number" && Number.isFinite(value.wards_placed) && Number.isInteger(value.wards_placed) || value.wards_placed === null) &&
    (typeof value.wards_killed === "number" && Number.isFinite(value.wards_killed) && Number.isInteger(value.wards_killed) || value.wards_killed === null) &&
    (typeof value.turret_damage === "number" && Number.isFinite(value.turret_damage) && Number.isInteger(value.turret_damage) || value.turret_damage === null) &&
    (typeof value.kill_participation_pct === "number" && Number.isFinite(value.kill_participation_pct) || value.kill_participation_pct === null) &&
    (typeof value.lane_opponent === "string" || value.lane_opponent === null) &&
    (typeof value.cs_delta === "number" && Number.isFinite(value.cs_delta) && Number.isInteger(value.cs_delta) || value.cs_delta === null) &&
    (typeof value.gold_delta === "number" && Number.isFinite(value.gold_delta) && Number.isInteger(value.gold_delta) || value.gold_delta === null);
}

export function isPlaybook(value: unknown): value is Playbook {
  return isRecord(value) &&
    value.schema_version === 2 &&
    typeof value.analysis_version === "string" &&
    typeof value.match_id === "string" &&
    (value.data_source === "riot" || value.data_source === "demo") &&
    (value.status === "ready" || value.status === "unsupported" || value.status === "insufficient_data") &&
    (typeof value.queue_id === "number" && Number.isFinite(value.queue_id) && Number.isInteger(value.queue_id) || value.queue_id === null) &&
    (typeof value.map_id === "number" && Number.isFinite(value.map_id) && Number.isInteger(value.map_id) || value.map_id === null) &&
    typeof value.patch === "string" &&
    Array.isArray(value.data_quality) && value.data_quality.every(item => typeof item === "string") &&
    typeof value.archetype === "string" &&
    typeof value.model_key === "string" &&
    typeof value.model_reason === "string" &&
    Array.isArray(value.model_evaluation) && value.model_evaluation.every(item => isEvaluation(item)) &&
    Array.isArray(value.composition) && value.composition.every(item => isPick(item)) &&
    Array.isArray(value.enemy_composition) && value.enemy_composition.every(item => isPick(item)) &&
    (isStats(value.match_stats) || value.match_stats === null) &&
    (isGamePlan(value.game_plan) || value.game_plan === null) &&
    Array.isArray(value.player_route) && value.player_route.every(item => isRoutePoint(item)) &&
    Array.isArray(value.events) && value.events.every(item => isEvent(item)) &&
    Array.isArray(value.decisions) && value.decisions.every(item => isDecision(item)) &&
    isHabitMetric(value.habit_metric) &&
    typeof value.saved === "boolean";
}

export function isAccount(value: unknown): value is Account {
  return isRecord(value) &&
    typeof value.puuid === "string" &&
    typeof value.gameName === "string" &&
    typeof value.tagLine === "string";
}

export function isPlayerMatches(value: unknown): value is PlayerMatches {
  return isRecord(value) &&
    isAccount(value.account) &&
    Array.isArray(value.matches) && value.matches.every(item => typeof item === "string");
}

export function isFeedbackSummary(value: unknown): value is FeedbackSummary {
  return isRecord(value) &&
    typeof value.decision === "string" &&
    (value.verdict === "agree" || value.verdict === "context" || value.verdict === "incorrect") &&
    typeof value.comment === "string" &&
    typeof value.match_id === "string" &&
    typeof value.created === "number" && Number.isFinite(value.created) && Number.isInteger(value.created);
}

export function isHabitProgress(value: unknown): value is HabitProgress {
  return isRecord(value) &&
    typeof value.started === "number" && Number.isFinite(value.started) && Number.isInteger(value.started) &&
    typeof value.version === "string" &&
    typeof value.completed === "number" && Number.isFinite(value.completed) && Number.isInteger(value.completed) && value.completed >= 0 && value.completed <= 5 &&
    value.target === 5 &&
    typeof value.numerator === "number" && Number.isFinite(value.numerator) && Number.isInteger(value.numerator) && value.numerator >= 0 &&
    typeof value.denominator === "number" && Number.isFinite(value.denominator) && Number.isInteger(value.denominator) && value.denominator >= 0;
}

export function isShareSummary(value: unknown): value is ShareSummary {
  return isRecord(value) &&
    typeof value.token === "string" &&
    typeof value.match_id === "string" &&
    typeof value.expires === "number" && Number.isFinite(value.expires) && Number.isInteger(value.expires);
}

export function isHistory(value: unknown): value is History {
  return isRecord(value) &&
    Array.isArray(value.analyses) && value.analyses.every(item => isPlaybook(item)) &&
    (isHabitProgress(value.habit) || value.habit === null) &&
    Array.isArray(value.shares) && value.shares.every(item => isShareSummary(item)) &&
    Array.isArray(value.feedback) && value.feedback.every(item => isFeedbackSummary(item));
}

export function isTrackedPlayer(value: unknown): value is TrackedPlayer {
  return isRecord(value) &&
    typeof value.puuid === "string" &&
    typeof value.name === "string";
}
